"""BF16-vs-FP8 frontier path comparison figures.

Consumes ``reports/fp8_frontier_path_analysis.json`` generated by
``python tools/introspect.py --mode compare-viz`` and emits two
publication-style figures:

  fig15_fp8_bf16_path_compare.png
  fig16_fp8_frontier_contributions.png
"""

from __future__ import annotations

import json
import textwrap
from pathlib import Path
from typing import Any

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt                              # noqa: E402
import matplotlib.patches as mpatches                       # noqa: E402
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch  # noqa: E402
import numpy as np                                           # noqa: E402

try:
    import seaborn as sns                                    # noqa: E402
except ImportError:
    sns = None


ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"
REPORT_JSON = ROOT / "reports" / "fp8_frontier_path_analysis.json"

C_BF16 = "#2563EB"
C_FP8 = "#EA580C"
C_SAVE = "#16A34A"
C_COST = "#DC2626"
C_NEUTRAL = "#64748B"
C_TEXT = "#0F172A"
C_GRID = "#E2E8F0"
C_CARD = "#FFFFFF"
C_PANEL = "#F8FAFC"
C_WARM = "#FFF7ED"
C_COOL = "#EFF6FF"

LABEL_MAP = {
    "GemmGated ZeroMat (fwd)": "ZeroMat gated GEMM (fwd)",
    "GemmDGated ZeroMat (bwd)": "ZeroMat dgated GEMM (bwd)",
    "Blockscaled Quant": "Blockscaled quant",
    "Dual Quant": "Dual quant",
    "Row Quant": "Row quant",
    "ISA Scale Gather": "ISA scale gather",
    "Token Gather": "Token gather",
    "TopK Router": "Top-k router",
    "Router Metadata": "Router metadata",
    "cuBLAS GEMM": "cuBLAS GEMM",
    "Reduce": "Reduce",
    "Elementwise Ops": "Elementwise ops",
    "GemmDGated (bwd)": "BF16 dgated GEMM",
    "GemmGated (fwd)": "BF16 gated GEMM",
    "Wgrad GEMM": "BF16 wgrad GEMM",
}


def _apply_style() -> None:
    if sns is not None:
        sns.set_style("whitegrid", {
            "grid.linestyle": "--",
            "grid.alpha": 0.20,
            "axes.edgecolor": "#CBD5E1",
        })
    plt.rcParams.update({
        "font.family": "serif",
        "font.serif": ["STIXGeneral", "DejaVu Serif"],
        "mathtext.fontset": "stix",
        "font.size": 10,
        "axes.titlesize": 12,
        "axes.labelsize": 10.5,
        "xtick.labelsize": 9,
        "ytick.labelsize": 9,
        "legend.fontsize": 8.6,
        "figure.dpi": 220,
        "savefig.dpi": 320,
        "savefig.bbox": "tight",
        "savefig.facecolor": "white",
        "axes.spines.top": False,
        "axes.spines.right": False,
    })


def _save(fig: plt.Figure, name: str) -> Path:
    ASSETS.mkdir(parents=True, exist_ok=True)
    out = ASSETS / name
    fig.savefig(out, pad_inches=0.18)
    plt.close(fig)
    print(f"    -> {out}")
    return out


def _load(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"comparison report not found: {path}")
    return json.loads(path.read_text())


def _wrap(text: str, width: int) -> str:
    return textwrap.fill(text, width=width, break_long_words=False, break_on_hyphens=False)


def _fmt_mib(value: float) -> str:
    return f"{value:.0f} MiB"


def _fmt_us(value: float) -> str:
    return f"{value:+.0f} us"


def _panel_label(ax: plt.Axes, label: str) -> None:
    ax.text(
        -0.02, 1.055, label, transform=ax.transAxes,
        ha="left", va="bottom", fontsize=12, fontweight="bold", color="#334155",
    )


def _tensor_color(dtype: str) -> str:
    lower = dtype.lower()
    if "fp8" in lower:
        return "#FFEDD5"
    if "bf16" in lower or "bfloat16" in lower:
        return "#DBEAFE"
    return "#E2E8F0"


def _summarize_outputs(outputs: list[str], limit: int = 3) -> str:
    if len(outputs) <= limit:
        return ", ".join(outputs)
    return ", ".join(outputs[:limit]) + f", +{len(outputs) - limit} more"


def _summarize_tensors(tensors: list[dict[str, Any]], limit: int = 2) -> str:
    if not tensors:
        return "No unique mode tensor."
    parts = [f"{t['name']} {t['size_mib']:.0f} MiB" for t in tensors[:limit]]
    if len(tensors) > limit:
        parts.append(f"+{len(tensors) - limit} more")
    return ", ".join(parts)


def _note_box(ax: plt.Axes, x: float, y: float, w: float, h: float, text: str,
              facecolor: str, edgecolor: str, fontsize: float = 8.2) -> None:
    patch = FancyBboxPatch(
        (x, y), w, h,
        boxstyle="round,pad=0.008,rounding_size=0.015",
        facecolor=facecolor, edgecolor=edgecolor, linewidth=0.9,
    )
    ax.add_patch(patch)
    ax.text(x + w / 2, y + h / 2, _wrap(text, 28),
            ha="center", va="center", fontsize=fontsize, color=C_TEXT)


def _draw_stage_card(ax: plt.Axes, x: float, y: float, w: float, h: float,
                     stage: dict[str, Any], mode: str, stage_num: int) -> None:
    accent = C_BF16 if mode == "bf16" else C_FP8
    fill = C_COOL if mode == "bf16" else C_WARM
    memory = stage["manifest_memory"][mode]
    outputs = stage[f"{mode}_outputs"]
    tensors = stage.get("bf16_only_tensors", []) if mode == "bf16" else stage.get("fp8_only_tensors", [])
    tensor_summary = _summarize_tensors(tensors)
    tensor_fill = _tensor_color(tensors[0]["dtype"]) if tensors else "#F1F5F9"

    patch = FancyBboxPatch(
        (x, y), w, h,
        boxstyle="round,pad=0.010,rounding_size=0.020",
        facecolor=C_CARD, edgecolor=accent, linewidth=1.6,
    )
    ax.add_patch(patch)
    ax.add_patch(FancyBboxPatch(
        (x + 0.010, y + h - 0.095), w - 0.020, 0.070,
        boxstyle="round,pad=0.004,rounding_size=0.012",
        facecolor=fill, edgecolor="none",
    ))
    ax.text(x + 0.020, y + h - 0.060, f"{stage_num}. {stage['name']}",
            ha="left", va="center", fontsize=8.8, fontweight="bold", color=accent)

    op_text = _wrap(stage[f"{mode}_core"], 29)
    outputs_text = _wrap("Outputs: " + _summarize_outputs(outputs, limit=3), 30)
    memory_text = f"Alloc {memory['allocated_mib']:.0f} MiB | Peak {memory['peak_mib']:.0f} MiB"
    ax.text(
        x + 0.018, y + h - 0.120,
        op_text + "\n\n" + outputs_text + "\n\n" + memory_text,
        ha="left", va="top", fontsize=7.15, color=C_TEXT, linespacing=1.28,
    )

    chip_h = 0.102
    chip_y = y - 0.145
    chip = FancyBboxPatch(
        (x + 0.012, chip_y), w - 0.024, chip_h,
        boxstyle="round,pad=0.006,rounding_size=0.014",
        facecolor=tensor_fill, edgecolor="#BFDBFE" if mode == "bf16" else "#FDBA74",
        linewidth=0.8,
    )
    ax.add_patch(chip)
    ax.text(
        x + w / 2, chip_y + chip_h / 2,
        _wrap(tensor_summary, 24),
        ha="center", va="center", fontsize=6.7, color=C_TEXT, linespacing=1.16,
    )


def _draw_stage_card_v(ax: plt.Axes, x0: float, y0: float,
                       w: float, h: float,
                       stage: dict[str, Any], mode: str, stage_num: int) -> None:
    """Draw a compact wide card for vertical lane layout."""
    accent = C_BF16 if mode == "bf16" else C_FP8
    header_fill = C_COOL if mode == "bf16" else C_WARM
    memory = stage["manifest_memory"][mode]
    hdr_h = h * 0.33

    # Card border
    ax.add_patch(FancyBboxPatch(
        (x0, y0), w, h,
        boxstyle="round,pad=0.005,rounding_size=0.010",
        facecolor="#FAFBFC", edgecolor=accent, linewidth=1.5, zorder=2,
    ))
    # Header strip
    ax.add_patch(FancyBboxPatch(
        (x0, y0 + h - hdr_h), w, hdr_h,
        boxstyle="square,pad=0.0",
        facecolor=header_fill, edgecolor="none", zorder=3,
        clip_path=None,
    ))
    # Stage number circle
    r_chip = hdr_h * 0.38
    cx = x0 + r_chip + 0.012
    cy = y0 + h - hdr_h / 2
    ax.add_patch(plt.Circle((cx, cy), r_chip, color=accent, alpha=0.18, zorder=4))
    ax.text(cx, cy, str(stage_num),
            ha="center", va="center", fontsize=7.2, fontweight="bold",
            color=accent, zorder=5)
    # Stage name
    ax.text(cx + r_chip + 0.010, cy, stage["name"],
            ha="left", va="center", fontsize=7.6, fontweight="bold",
            color=accent, zorder=5)
    # Core op text
    core = _wrap(stage[f"{mode}_core"], 64)
    ax.text(x0 + 0.012, y0 + h - hdr_h - 0.008, core,
            ha="left", va="top", fontsize=5.9, color=C_TEXT,
            linespacing=1.18, zorder=4)
    # Memory line at bottom
    mem_str = (f"Alloc {memory['allocated_mib']:.0f} MiB  |  "
               f"Peak {memory['peak_mib']:.0f} MiB")
    ax.text(x0 + w - 0.010, y0 + 0.008, mem_str,
            ha="right", va="bottom", fontsize=5.5, color=C_NEUTRAL,
            style="italic", zorder=4)


def _draw_lane_v(ax: plt.Axes, stages: list[dict[str, Any]], mode: str) -> None:
    """Draw the 6 stages vertically (top-to-bottom) for fig15."""
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.axis("off")

    accent = C_BF16 if mode == "bf16" else C_FP8
    title = "BF16 Baseline Path" if mode == "bf16" else "FP8 Frontier Path"
    subtitle = (
        "Canonical BF16 operator flow with BF16 activation bridges."
        if mode == "bf16"
        else "Zero-materialization frontier: T-size quant + ZeroMat GEMM + FP8 bridges."
    )
    x0, card_w = 0.03, 0.94
    card_h = 0.109
    arrow_gap = 0.022
    slot_h = card_h + arrow_gap
    y_top_first = 0.900     # top edge of first card

    ax.text(0.50, 0.975, title, ha="center", va="top",
            fontsize=12, fontweight="bold", color=accent)
    ax.text(0.50, 0.950, subtitle, ha="center", va="top",
            fontsize=7.8, color=C_NEUTRAL, linespacing=1.25)

    # FWD / BWD section labels
    fwd_mid_y = y_top_first - 1.5 * slot_h    # midpoint of first 3 cards
    bwd_mid_y = y_top_first - 4.0 * slot_h    # midpoint of last 3 cards
    ax.text(-0.005, fwd_mid_y, "FWD", ha="right", va="center",
            fontsize=8, fontweight="bold", color=accent, alpha=0.65, rotation=90)
    ax.text(-0.005, bwd_mid_y, "BWD", ha="right", va="center",
            fontsize=8, fontweight="bold", color=accent, alpha=0.65, rotation=90)

    for i, stage in enumerate(stages):
        card_top = y_top_first - i * slot_h
        card_y0  = card_top - card_h          # bottom-left corner for Patch

        # FWD / BWD divider between stage 3 (i=2) and stage 4 (i=3)
        if i == 3:
            div_y = card_top + arrow_gap / 2
            ax.plot([0.03, 0.97], [div_y, div_y],
                    color="#94A3B8", linewidth=0.9, linestyle="--", zorder=1)
            lbl_w = 0.18
            ax.add_patch(FancyBboxPatch(
                (0.5 - lbl_w / 2, div_y - 0.012), lbl_w, 0.024,
                boxstyle="round,pad=0.003", facecolor="white",
                edgecolor="#94A3B8", linewidth=0.7, zorder=2,
            ))
            ax.text(0.5, div_y, "\u2193 BACKWARD",
                    ha="center", va="center", fontsize=6.8,
                    fontweight="bold", color=accent, alpha=0.85, zorder=3)

        # Downward arrow from previous card to this card
        if i > 0:
            arr_start_y = card_top + arrow_gap
            arr_end_y   = card_top + 0.003
            ax.add_patch(FancyArrowPatch(
                (0.5, arr_start_y), (0.5, arr_end_y),
                arrowstyle="-|>", mutation_scale=7,
                linewidth=0.9, color=accent, alpha=0.65, zorder=2,
            ))

        _draw_stage_card_v(ax, x0, card_y0, card_w, card_h, stage, mode, i + 1)

    # Footer note
    footer = (
        "BF16 keeps z and dz in BF16; TK-size HBM buffers are materialized."
        if mode == "bf16"
        else "Only T-size FP8 buffers used; gathered TK-size HBM is never materialized."
    )
    footer_fill = "#EFF6FF" if mode == "bf16" else "#FFF7ED"
    footer_edge = "#93C5FD" if mode == "bf16" else "#FDBA74"
    bot = y_top_first - 6 * slot_h + 0.002
    ax.add_patch(FancyBboxPatch(
        (x0, bot), card_w, 0.038,
        boxstyle="round,pad=0.005", facecolor=footer_fill,
        edgecolor=footer_edge, linewidth=0.8, zorder=2,
    ))
    ax.text(0.5, bot + 0.019, footer,
            ha="center", va="center", fontsize=6.5,
            color=C_TEXT, linespacing=1.15, zorder=3)

    footer = (
        "BF16 keeps z and dz in BF16 through the backward tail."
        if mode == "bf16"
        else "Only scales are gathered to TK; gathered TK-sized FP8 activations are never materialized in HBM."
    )
    footer_face = "#EFF6FF" if mode == "bf16" else "#FFF7ED"
    footer_edge = "#93C5FD" if mode == "bf16" else "#FDBA74"
    _note_box(ax, 0.28, 0.02, 0.44, 0.085, footer, footer_face, footer_edge, fontsize=8.1)


def _draw_summary_panel(ax: plt.Axes, report: dict[str, Any]) -> None:
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.axis("off")

    frontier = report["frontier_summary"]
    budget = report["budget_anchor"]
    precision = report["precision_anchor"]
    peaks = report["path_analysis"]["scoreboard_hints"]["peaks"]

    cards = [
        (
            "27-shape frontier",
            [
                f"Speedup range: {frontier['speedup_range']['min']:.2f}x to {frontier['speedup_range']['max']:.2f}x",
                f"Mean speedup: {frontier['speedup_range']['mean']:.2f}x",
                f"Bwd memory delta: {frontier['memory_bwd_delta_pct_range']['min']:.1f}% to {frontier['memory_bwd_delta_pct_range']['max']:.1f}%",
            ],
            C_PANEL,
            "#CBD5E1",
        ),
        (
            "Representative anchor",
            [
                budget["shape_key"],
                f"BF16 {budget['bf16_us']:.0f} us -> FP8 {budget['fp8_us']:.0f} us",
                f"Net contribution: {_fmt_us(budget['budget_totals']['net_us'])}",
            ],
            "#FFF7ED",
            "#FDBA74",
        ),
        (
            "Precision anchor",
            [
                precision["shape_key"],
                f"Max RRMSE: {precision['max_rrmse_pct']:.2f}%",
                f"Min cosine: {precision['min_cosine_sim']:.5f}",
            ],
            "#F0FDF4",
            "#86EFAC",
        ),
        (
            "Scoreboard peaks",
            [
                f"BF16: {peaks['bf16']['name']} ({peaks['bf16']['alloc_mib']:.0f} MiB)",
                f"FP8: {peaks['fp8']['name']} ({peaks['fp8']['alloc_mib']:.0f} MiB)",
            ],
            "#FEF2F2",
            "#FCA5A5",
        ),
    ]

    y = 0.96
    heights = [0.19, 0.19, 0.17, 0.15]
    for (title, lines, face, edge), h in zip(cards, heights):
        y0 = y - h
        patch = FancyBboxPatch(
            (0.02, y0), 0.96, h,
            boxstyle="round,pad=0.010,rounding_size=0.018",
            facecolor=face, edgecolor=edge, linewidth=0.9,
        )
        ax.add_patch(patch)
        ax.text(0.06, y0 + h - 0.05, title, ha="left", va="top",
                fontsize=9.2, fontweight="bold", color=C_TEXT)
        ax.text(0.06, y0 + h - 0.10, "\n".join(lines), ha="left", va="top",
                fontsize=8.0, color=C_TEXT, linespacing=1.32)
        y = y0 - 0.035


def _plot_phase_memory(ax: plt.Axes, report: dict[str, Any]) -> None:
    bf16 = report["path_analysis"]["phase_memory"]["bf16"]
    fp8 = report["path_analysis"]["phase_memory"]["fp8"]
    phase_names = ["Router", "UpProj Fwd", "DnProj Fwd", "DnProj Bwd", "UpBwd (wg)", "UpBwd (ag)"]
    x = np.arange(len(phase_names))

    bf16_alloc = np.array([row["allocated_mib"] for row in bf16], dtype=float)
    bf16_peak = np.array([row["peak_mib"] for row in bf16], dtype=float)
    fp8_alloc = np.array([row["allocated_mib"] for row in fp8], dtype=float)
    fp8_peak = np.array([row["peak_mib"] for row in fp8], dtype=float)

    ax.set_facecolor("#FCFCFD")
    ax.axvspan(0.75, 3.25, color="#FFF7ED", alpha=0.85)
    ax.text(2.0, max(fp8_peak) * 0.985, "FP8 quant / bridge frontier", ha="center", va="top",
            fontsize=8.8, color="#9A3412")

    ax.plot(x, bf16_alloc, marker="o", color=C_BF16, linewidth=2.1, label="BF16 allocated")
    ax.plot(x, bf16_peak, marker="o", color=C_BF16, linewidth=1.7, linestyle="--", label="BF16 peak")
    ax.plot(x, fp8_alloc, marker="s", color=C_FP8, linewidth=2.1, label="FP8 allocated")
    ax.plot(x, fp8_peak, marker="s", color=C_FP8, linewidth=1.7, linestyle="--", label="FP8 peak")

    bf16_idx = int(np.argmax(bf16_peak))
    fp8_idx = int(np.argmax(fp8_peak))
    ax.annotate(
        f"BF16 peak\n{_fmt_mib(bf16_peak[bf16_idx])}",
        xy=(bf16_idx, bf16_peak[bf16_idx]),
        xytext=(bf16_idx - 0.55, bf16_peak[bf16_idx] + 110),
        arrowprops=dict(arrowstyle="->", color=C_BF16, lw=1.0),
        fontsize=8.2, color=C_BF16, ha="left",
    )
    ax.annotate(
        f"FP8 peak\n{_fmt_mib(fp8_peak[fp8_idx])}",
        xy=(fp8_idx, fp8_peak[fp8_idx]),
        xytext=(fp8_idx + 0.15, fp8_peak[fp8_idx] + 135),
        arrowprops=dict(arrowstyle="->", color=C_FP8, lw=1.0),
        fontsize=8.2, color=C_FP8, ha="left",
    )

    ax.set_title("Phase-wise memory envelope from manifest.json", loc="left")
    ax.set_ylabel("MiB")
    ax.set_xticks(x)
    ax.set_xticklabels(phase_names, rotation=16, ha="right")
    ax.grid(True, axis="y", color=C_GRID)
    ax.legend(ncols=4, loc="upper left", frameon=False)


def _plot_budget_waterfall(ax: plt.Axes, budget: dict[str, Any]) -> None:
    rows = sorted(budget["budget_breakdown"], key=lambda row: row["delta_us"])
    labels = [LABEL_MAP.get(row["category"], row["category"]) for row in rows]
    vals = np.array([row["delta_us"] for row in rows], dtype=float)
    ypos = np.arange(len(rows))
    colors = [C_SAVE if v < 0 else C_COST for v in vals]

    pad = max(abs(vals.min()), abs(vals.max())) * 0.09 + 55
    ax.set_xlim(vals.min() - pad, vals.max() + pad)
    ax.set_facecolor("#FCFCFD")
    ax.barh(ypos, vals, color=colors, alpha=0.88, edgecolor="none")
    ax.axvline(0, color=C_TEXT, linewidth=1.0)
    ax.set_yticks(ypos)
    ax.set_yticklabels(labels)
    ax.set_xlabel("FP8 - BF16 (us / iter)")
    ax.set_title(f"Representative budget delta - {budget['shape_key']}", loc="left")
    ax.grid(True, axis="x", color=C_GRID)
    for y, value in zip(ypos, vals):
        ax.text(
            value + (14 if value >= 0 else -14), y, _fmt_us(value),
            va="center", ha="left" if value >= 0 else "right", fontsize=8,
        )
    net = budget["budget_totals"]["net_us"]
    ax.text(
        0.98, 0.03,
        f"Savings {budget['budget_totals']['savings_us']:.0f} us\n"
        f"Overhead {budget['budget_totals']['overhead_us']:.0f} us\n"
        f"Net {_fmt_us(net)}",
        transform=ax.transAxes,
        ha="right", va="bottom", fontsize=8.3,
        bbox=dict(boxstyle="round,pad=0.30", facecolor=C_PANEL, edgecolor="#CBD5E1"),
    )


def _compute_specific_sweeps(grid_records: list[dict[str, Any]]) -> dict[str, Any]:
    """Build 6 specific sweeps (2 per dimension) from the 27-shape grid."""
    lookup: dict[tuple[int, int, int], float] = {}
    for rec in grid_records:
        lookup[(int(rec["T"]), int(rec["E"]), int(rec["I"]))] = float(rec["speedup"])

    def _sweep(dim: str, values: list, fixed: dict[str, int]) -> list[float]:
        out = []
        for v in values:
            key_dict = dict(fixed)
            key_dict[dim] = v
            k = (key_dict["T"], key_dict["E"], key_dict["I"])
            out.append(lookup.get(k, float("nan")))
        return out

    return {
        "T_low_I":  {"vals": _sweep("T", [8192, 16384, 32768], {"E": 8, "I": 1536}),
                     "labels": ["8k", "16k", "32k"], "fixed": "E=8, I=1536"},
        "T_high_I": {"vals": _sweep("T", [8192, 16384, 32768], {"E": 8, "I": 3072}),
                     "labels": ["8k", "16k", "32k"], "fixed": "E=8, I=3072"},
        "I_low_T":  {"vals": _sweep("I", [1536, 2048, 3072], {"T": 8192,  "E": 8}),
                     "labels": ["1536", "2048", "3072"], "fixed": "T=8k, E=8"},
        "I_high_T": {"vals": _sweep("I", [1536, 2048, 3072], {"T": 32768, "E": 8}),
                     "labels": ["1536", "2048", "3072"], "fixed": "T=32k, E=8"},
        "E_low_T":  {"vals": _sweep("E", [8, 32, 128], {"T": 8192,  "I": 1536}),
                     "labels": ["8", "32", "128"], "fixed": "T=8k, I=1536"},
        "E_high_T": {"vals": _sweep("E", [8, 32, 128], {"T": 32768, "I": 3072}),
                     "labels": ["8", "32", "128"], "fixed": "T=32k, I=3072"},
    }


def _plot_dimension_bars(ax: plt.Axes, frontier_summary: dict[str, Any],
                         precision: dict[str, Any],
                         grid_records: list[dict[str, Any]]) -> None:
    """Paired grouped bars showing speedup sweeps for each dimension.
    Each dimension has two bars (two parameterizations) side-by-side.
    """
    sweeps = _compute_specific_sweeps(grid_records)

    # Layout: 3 dimension groups, each with 2 sub-sweeps, each with 3 values
    dim_groups = [
        ("Token count  T", [
            (sweeps["T_low_I"],  "#93C5FD", "E=8, I=1536"),
            (sweeps["T_high_I"], "#1D4ED8", "E=8, I=3072"),
        ]),
        ("Interm. size  I", [
            (sweeps["I_low_T"],  "#86EFAC", "T=8k, E=8"),
            (sweeps["I_high_T"], "#166534", "T=32k, E=8"),
        ]),
        ("Expert count  E", [
            (sweeps["E_low_T"],  "#FCA5A5", "T=8k, I=1536"),
            (sweeps["E_high_T"], "#991B1B", "T=32k, I=3072"),
        ]),
    ]

    xpos_all: list[float] = []
    vals_all: list[float] = []
    colors_all: list[str] = []
    tick_labels_all: list[str] = []
    group_spans: list[tuple[float, float, str]] = []
    legend_handles: list[Any] = []
    x = 0.0
    bar_w = 0.32

    for dim_name, sweeps_pair in dim_groups:
        group_start = x - 0.5
        s0, c0, lab0 = sweeps_pair[0]
        s1, c1, lab1 = sweeps_pair[1]
        n = len(s0["vals"])
        for k in range(n):
            xpos_all.append(x - bar_w / 2)
            xpos_all.append(x + bar_w / 2)
            vals_all.append(s0["vals"][k])
            vals_all.append(s1["vals"][k])
            colors_all.append(c0)
            colors_all.append(c1)
            tick_labels_all.append(s0["labels"][k])
            tick_labels_all.append("")
            x += 1.0
        group_spans.append((group_start, x - 0.52, dim_name))
        x += 0.80

        legend_handles.append(mpatches.Patch(color=c0, label=lab0))
        legend_handles.append(mpatches.Patch(color=c1, label=lab1))

    ax.set_facecolor("#FCFCFD")
    bg_colors = ["#EFF6FF", "#F0FDF4", "#FFF1F2"]
    for (start, end, label), bg in zip(group_spans, bg_colors):
        ax.axvspan(start, end, color=bg, alpha=0.80, zorder=0)
        ax.text((start + end) / 2, 1.025, label,
                transform=ax.get_xaxis_transform(),
                ha="center", va="bottom", fontsize=9, color=C_NEUTRAL,
                fontweight="bold")

    ax.bar(xpos_all, vals_all, width=bar_w * 0.90,
           color=colors_all, edgecolor="white", linewidth=0.4)

    mean_speed = frontier_summary["speedup_range"]["mean"]
    ax.axhline(mean_speed, color=C_TEXT, linestyle="--", linewidth=1.0,
               label=f"global mean {mean_speed:.2f}×")
    ax.set_ylabel("FP8 speedup (×)")
    ax.set_title(
        "Scaling: speedup under fixed-parameter sweeps  (paired: light=low, dark=high config)",
        loc="left", fontsize=9,
    )
    ax.set_xticks(xpos_all[::2])
    ax.set_xticklabels(tick_labels_all[::2])
    ax.set_ylim(1.00, max(v for v in vals_all if not np.isnan(v)) + 0.18)
    ax.grid(True, axis="y", color=C_GRID)
    for xp, val in zip(xpos_all, vals_all):
        if not np.isnan(val):
            ax.text(xp, val + 0.012, f"{val:.3f}×",
                    ha="center", va="bottom", fontsize=7.0)
    legend_handles.append(
        mpatches.Patch(color="none", label=f"global mean {mean_speed:.2f}×")
    )
    ax.legend(handles=legend_handles, frameon=True, framealpha=0.88,
              loc="upper left", fontsize=7.5, ncol=2)
    ax.text(
        0.99, 0.06,
        f"Precision anchor: {precision['shape_key']}\n"
        f"Max RRMSE {precision['max_rrmse_pct']:.2f}%  |  "
        f"Min cosine {precision['min_cosine_sim']:.5f}",
        transform=ax.transAxes,
        ha="right", va="bottom", fontsize=7.5,
        bbox=dict(boxstyle="round,pad=0.25", facecolor=C_PANEL, edgecolor="#CBD5E1"),
    )


def _heatmap(ax: plt.Axes, payload: dict[str, Any], title: str, xlabel: str, ylabel: str,
             cmap: str, fmt: str, annotate_suffix: str, cbar_label: str) -> None:
    data = np.array(payload["values"], dtype=float)
    im = ax.imshow(data, cmap=cmap, aspect="auto")
    ax.set_title(title, loc="left")
    ax.set_xticks(np.arange(len(payload["cols"])))
    ax.set_yticks(np.arange(len(payload["rows"])))
    ax.set_xticklabels(payload["cols"])
    ax.set_yticklabels(payload["rows"])
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    ax.set_xticks(np.arange(-0.5, data.shape[1], 1), minor=True)
    ax.set_yticks(np.arange(-0.5, data.shape[0], 1), minor=True)
    ax.grid(which="minor", color="white", linestyle="-", linewidth=1.2)
    ax.tick_params(which="minor", bottom=False, left=False)

    lo = float(np.min(data))
    hi = float(np.max(data))
    mid = (lo + hi) / 2.0
    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            color = "white" if data[i, j] > mid else C_TEXT
            ax.text(
                j, i, format(data[i, j], fmt) + annotate_suffix,
                ha="center", va="center", fontsize=8.2, color=color,
            )
    cbar = plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    cbar.set_label(cbar_label, rotation=90)


def _render_path_compare(report: dict[str, Any]) -> Path:
    """fig15 — vertical dual-lane layout: BF16 (left) | FP8 (right) | side panel."""
    _apply_style()
    fig = plt.figure(figsize=(17, 22))
    gs = fig.add_gridspec(
        2, 3,
        width_ratios=[1.0, 1.0, 0.56],
        height_ratios=[3.1, 1.0],
        hspace=0.10, wspace=0.08,
    )
    ax_bf16 = fig.add_subplot(gs[0, 0])
    ax_fp8  = fig.add_subplot(gs[0, 1])
    ax_side = fig.add_subplot(gs[0, 2])
    ax_mem  = fig.add_subplot(gs[1, :2])
    ax_foot = fig.add_subplot(gs[1, 2])

    stages = report["path_analysis"]["stage_deltas"]
    _panel_label(ax_bf16, "(a)")
    _panel_label(ax_fp8,  "(b)")
    _panel_label(ax_mem,  "(c)")

    _draw_lane_v(ax_bf16, stages, "bf16")
    _draw_lane_v(ax_fp8,  stages, "fp8")
    _draw_summary_panel(ax_side, report)
    _plot_phase_memory(ax_mem, report)

    ax_foot.axis("off")
    ax_foot.text(
        0.5, 0.5,
        "Stage memory shows allocated + peak\n"
        "HBM (MiB) for each phase.\n\n"
        "FP8 frontier eliminates TK-size\n"
        "gathered activation buffers by\n"
        "using T-size quant + ZeroMat GEMM.",
        ha="center", va="center", fontsize=9.5, color=C_NEUTRAL,
        linespacing=1.55,
        bbox=dict(boxstyle="round,pad=0.5", facecolor=C_PANEL, edgecolor="#CBD5E1"),
    )

    fig.suptitle(
        "SonicMoE  —  BF16 vs FP8 Frontier: Operator Path, Bridge Tensors, Memory Envelope",
        fontsize=16, fontweight="bold", y=0.992,
    )
    fig.text(
        0.5, 0.975,
        "Representative flow: manifest.json + scoreboard.json  |  "
        "Frontier stats: Session 53 nsys 27-shape grid",
        ha="center", fontsize=9, color=C_NEUTRAL,
    )
    return _save(fig, "fig15_fp8_bf16_path_compare.png")


def _render_frontier_contributions(report: dict[str, Any]) -> Path:
    """fig16 — redesigned: specific-sweep grouped bars + two heatmaps."""
    _apply_style()
    fig = plt.figure(figsize=(17.5, 12.4))
    gs = fig.add_gridspec(2, 2, height_ratios=[1.05, 1.0], hspace=0.34, wspace=0.26)
    ax_budget = fig.add_subplot(gs[0, 0])
    ax_dim    = fig.add_subplot(gs[0, 1])
    ax_mem_h  = fig.add_subplot(gs[1, 0])   # memory-delta T×I heatmap
    ax_ei_h   = fig.add_subplot(gs[1, 1])   # E×I heatmap

    _panel_label(ax_budget, "(a)")
    _panel_label(ax_dim,    "(b)")
    _panel_label(ax_mem_h,  "(c)")
    _panel_label(ax_ei_h,   "(d)")

    _plot_budget_waterfall(ax_budget, report["budget_anchor"])
    _plot_dimension_bars(
        ax_dim,
        report["frontier_summary"],
        report["precision_anchor"],
        report["grid_records"],
    )

    # (c) Memory-delta T×I averaged over E — built from grid_records
    grid_records = report["grid_records"]
    T_vals = sorted(set(int(r["T"]) for r in grid_records))
    I_vals = sorted(set(int(r["I"]) for r in grid_records))
    mat_mem = np.zeros((len(T_vals), len(I_vals)))
    for ti, T in enumerate(T_vals):
        for ii, I in enumerate(I_vals):
            vals = [float(r["peak_bwd_delta_pct"]) for r in grid_records
                    if int(r["T"]) == T and int(r["I"]) == I]
            mat_mem[ti, ii] = float(np.mean(vals)) if vals else 0.0
    mem_payload = {
        "values": mat_mem.tolist(),
        "rows": [f"T={t//1024}k" for t in T_vals],
        "cols": [f"I={i}" for i in I_vals],
    }
    _heatmap(
        ax_mem_h, mem_payload,
        "Memory delta  T×I  averaged over E",
        xlabel="Intermediate size I", ylabel="Tokens T",
        cmap="YlOrRd", fmt=".1f", annotate_suffix="%",
        cbar_label="Peak bwd memory Δ (%)",
    )
    ax_mem_h.text(
        0.5, -0.10,
        "Positive = FP8 uses more peak backward HBM than BF16  "
        "(wgrad quant temporaries)",
        transform=ax_mem_h.transAxes, ha="center", va="top",
        fontsize=7.8, color=C_NEUTRAL, style="italic",
    )

    # (d) E×I speedup heatmap averaged over T
    _heatmap(
        ax_ei_h,
        report["heatmaps"]["memory_delta_E_I_avg_over_T"],
        "Memory delta  E×I  averaged over T",
        xlabel="Intermediate size I", ylabel="Experts E",
        cmap="YlOrRd", fmt=".1f", annotate_suffix="%",
        cbar_label="Peak bwd memory Δ (%)",
    )

    fig.suptitle(
        "FP8 Frontier over BF16  —  Contribution Decomposition & Scaling Landscape",
        fontsize=16, fontweight="bold", y=0.992,
    )
    fig.text(
        0.5, 0.972,
        "Negative budget deltas = FP8 savings; positive = quant + bridge overhead.  "
        "Scaling bars use explicit fixed-parameter sweeps.",
        ha="center", fontsize=9, color=C_NEUTRAL,
    )
    return _save(fig, "fig16_fp8_frontier_contributions.png")


def generate_compare_viz(report_path: Path = REPORT_JSON) -> list[Path]:
    report = _load(report_path)
    return [
        _render_path_compare(report),
        _render_frontier_contributions(report),
    ]


if __name__ == "__main__":
    generate_compare_viz()
